name: CI + Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        pip install -r requirements.txt
        pip install coverage

    - name: run tests and coverage
      run: |
        coverage run -m pytest tests/
        coverage xml

    - name: upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Only needed for private repos
        files: coverage.xml
        fail_ci_if_error: true
